// export by github.com/goplus/ixgo/cmd/qexp

package server

import (
	q "github.com/mark3labs/mcp-go/server"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "server",
		Path: "github.com/mark3labs/mcp-go/server",
		Deps: map[string]string{
			"bufio":                            "bufio",
			"bytes":                            "bytes",
			"cmp":                              "cmp",
			"context":                          "context",
			"encoding/base64":                  "base64",
			"encoding/json":                    "json",
			"errors":                           "errors",
			"fmt":                              "fmt",
			"github.com/google/uuid":           "uuid",
			"github.com/mark3labs/mcp-go/mcp":  "mcp",
			"github.com/mark3labs/mcp-go/util": "util",
			"io":                               "io",
			"log":                              "log",
			"maps":                             "maps",
			"mime":                             "mime",
			"net/http":                         "http",
			"net/http/httptest":                "httptest",
			"net/url":                          "url",
			"os":                               "os",
			"os/signal":                        "signal",
			"path":                             "path",
			"slices":                           "slices",
			"sort":                             "sort",
			"strings":                          "strings",
			"sync":                             "sync",
			"sync/atomic":                      "atomic",
			"syscall":                          "syscall",
			"time":                             "time",
			"unicode":                          "unicode",
		},
		Interfaces: map[string]reflect.Type{
			"ClientSession":                   reflect.TypeOf((*q.ClientSession)(nil)).Elem(),
			"ElicitationHandler":              reflect.TypeOf((*q.ElicitationHandler)(nil)).Elem(),
			"RootsHandler":                    reflect.TypeOf((*q.RootsHandler)(nil)).Elem(),
			"SamplingHandler":                 reflect.TypeOf((*q.SamplingHandler)(nil)).Elem(),
			"SessionIdManager":                reflect.TypeOf((*q.SessionIdManager)(nil)).Elem(),
			"SessionIdManagerResolver":        reflect.TypeOf((*q.SessionIdManagerResolver)(nil)).Elem(),
			"SessionWithClientInfo":           reflect.TypeOf((*q.SessionWithClientInfo)(nil)).Elem(),
			"SessionWithElicitation":          reflect.TypeOf((*q.SessionWithElicitation)(nil)).Elem(),
			"SessionWithLogging":              reflect.TypeOf((*q.SessionWithLogging)(nil)).Elem(),
			"SessionWithResourceTemplates":    reflect.TypeOf((*q.SessionWithResourceTemplates)(nil)).Elem(),
			"SessionWithResources":            reflect.TypeOf((*q.SessionWithResources)(nil)).Elem(),
			"SessionWithRoots":                reflect.TypeOf((*q.SessionWithRoots)(nil)).Elem(),
			"SessionWithSampling":             reflect.TypeOf((*q.SessionWithSampling)(nil)).Elem(),
			"SessionWithStreamableHTTPConfig": reflect.TypeOf((*q.SessionWithStreamableHTTPConfig)(nil)).Elem(),
			"SessionWithTools":                reflect.TypeOf((*q.SessionWithTools)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"BeforeAnyHookFunc":                   reflect.TypeOf((*q.BeforeAnyHookFunc)(nil)).Elem(),
			"DefaultSessionIdManagerResolver":     reflect.TypeOf((*q.DefaultSessionIdManagerResolver)(nil)).Elem(),
			"DynamicBasePathFunc":                 reflect.TypeOf((*q.DynamicBasePathFunc)(nil)).Elem(),
			"ErrDynamicPathConfig":                reflect.TypeOf((*q.ErrDynamicPathConfig)(nil)).Elem(),
			"HTTPContextFunc":                     reflect.TypeOf((*q.HTTPContextFunc)(nil)).Elem(),
			"Hooks":                               reflect.TypeOf((*q.Hooks)(nil)).Elem(),
			"InProcessSession":                    reflect.TypeOf((*q.InProcessSession)(nil)).Elem(),
			"InsecureStatefulSessionIdManager":    reflect.TypeOf((*q.InsecureStatefulSessionIdManager)(nil)).Elem(),
			"MCPServer":                           reflect.TypeOf((*q.MCPServer)(nil)).Elem(),
			"NotificationHandlerFunc":             reflect.TypeOf((*q.NotificationHandlerFunc)(nil)).Elem(),
			"OnAfterCallToolFunc":                 reflect.TypeOf((*q.OnAfterCallToolFunc)(nil)).Elem(),
			"OnAfterGetPromptFunc":                reflect.TypeOf((*q.OnAfterGetPromptFunc)(nil)).Elem(),
			"OnAfterInitializeFunc":               reflect.TypeOf((*q.OnAfterInitializeFunc)(nil)).Elem(),
			"OnAfterListPromptsFunc":              reflect.TypeOf((*q.OnAfterListPromptsFunc)(nil)).Elem(),
			"OnAfterListResourceTemplatesFunc":    reflect.TypeOf((*q.OnAfterListResourceTemplatesFunc)(nil)).Elem(),
			"OnAfterListResourcesFunc":            reflect.TypeOf((*q.OnAfterListResourcesFunc)(nil)).Elem(),
			"OnAfterListToolsFunc":                reflect.TypeOf((*q.OnAfterListToolsFunc)(nil)).Elem(),
			"OnAfterPingFunc":                     reflect.TypeOf((*q.OnAfterPingFunc)(nil)).Elem(),
			"OnAfterReadResourceFunc":             reflect.TypeOf((*q.OnAfterReadResourceFunc)(nil)).Elem(),
			"OnAfterSetLevelFunc":                 reflect.TypeOf((*q.OnAfterSetLevelFunc)(nil)).Elem(),
			"OnBeforeCallToolFunc":                reflect.TypeOf((*q.OnBeforeCallToolFunc)(nil)).Elem(),
			"OnBeforeGetPromptFunc":               reflect.TypeOf((*q.OnBeforeGetPromptFunc)(nil)).Elem(),
			"OnBeforeInitializeFunc":              reflect.TypeOf((*q.OnBeforeInitializeFunc)(nil)).Elem(),
			"OnBeforeListPromptsFunc":             reflect.TypeOf((*q.OnBeforeListPromptsFunc)(nil)).Elem(),
			"OnBeforeListResourceTemplatesFunc":   reflect.TypeOf((*q.OnBeforeListResourceTemplatesFunc)(nil)).Elem(),
			"OnBeforeListResourcesFunc":           reflect.TypeOf((*q.OnBeforeListResourcesFunc)(nil)).Elem(),
			"OnBeforeListToolsFunc":               reflect.TypeOf((*q.OnBeforeListToolsFunc)(nil)).Elem(),
			"OnBeforePingFunc":                    reflect.TypeOf((*q.OnBeforePingFunc)(nil)).Elem(),
			"OnBeforeReadResourceFunc":            reflect.TypeOf((*q.OnBeforeReadResourceFunc)(nil)).Elem(),
			"OnBeforeSetLevelFunc":                reflect.TypeOf((*q.OnBeforeSetLevelFunc)(nil)).Elem(),
			"OnErrorHookFunc":                     reflect.TypeOf((*q.OnErrorHookFunc)(nil)).Elem(),
			"OnRegisterSessionHookFunc":           reflect.TypeOf((*q.OnRegisterSessionHookFunc)(nil)).Elem(),
			"OnRequestInitializationFunc":         reflect.TypeOf((*q.OnRequestInitializationFunc)(nil)).Elem(),
			"OnSuccessHookFunc":                   reflect.TypeOf((*q.OnSuccessHookFunc)(nil)).Elem(),
			"OnUnregisterSessionHookFunc":         reflect.TypeOf((*q.OnUnregisterSessionHookFunc)(nil)).Elem(),
			"PromptHandlerFunc":                   reflect.TypeOf((*q.PromptHandlerFunc)(nil)).Elem(),
			"ResourceHandlerFunc":                 reflect.TypeOf((*q.ResourceHandlerFunc)(nil)).Elem(),
			"ResourceHandlerMiddleware":           reflect.TypeOf((*q.ResourceHandlerMiddleware)(nil)).Elem(),
			"ResourceTemplateHandlerFunc":         reflect.TypeOf((*q.ResourceTemplateHandlerFunc)(nil)).Elem(),
			"SSEContextFunc":                      reflect.TypeOf((*q.SSEContextFunc)(nil)).Elem(),
			"SSEOption":                           reflect.TypeOf((*q.SSEOption)(nil)).Elem(),
			"SSEServer":                           reflect.TypeOf((*q.SSEServer)(nil)).Elem(),
			"ServerOption":                        reflect.TypeOf((*q.ServerOption)(nil)).Elem(),
			"ServerPrompt":                        reflect.TypeOf((*q.ServerPrompt)(nil)).Elem(),
			"ServerResource":                      reflect.TypeOf((*q.ServerResource)(nil)).Elem(),
			"ServerResourceTemplate":              reflect.TypeOf((*q.ServerResourceTemplate)(nil)).Elem(),
			"ServerTool":                          reflect.TypeOf((*q.ServerTool)(nil)).Elem(),
			"StatelessGeneratingSessionIdManager": reflect.TypeOf((*q.StatelessGeneratingSessionIdManager)(nil)).Elem(),
			"StatelessSessionIdManager":           reflect.TypeOf((*q.StatelessSessionIdManager)(nil)).Elem(),
			"StdioContextFunc":                    reflect.TypeOf((*q.StdioContextFunc)(nil)).Elem(),
			"StdioOption":                         reflect.TypeOf((*q.StdioOption)(nil)).Elem(),
			"StdioServer":                         reflect.TypeOf((*q.StdioServer)(nil)).Elem(),
			"StreamableHTTPOption":                reflect.TypeOf((*q.StreamableHTTPOption)(nil)).Elem(),
			"StreamableHTTPServer":                reflect.TypeOf((*q.StreamableHTTPServer)(nil)).Elem(),
			"ToolFilterFunc":                      reflect.TypeOf((*q.ToolFilterFunc)(nil)).Elem(),
			"ToolHandlerFunc":                     reflect.TypeOf((*q.ToolHandlerFunc)(nil)).Elem(),
			"ToolHandlerMiddleware":               reflect.TypeOf((*q.ToolHandlerMiddleware)(nil)).Elem(),
			"UnparsableMessageError":              reflect.TypeOf((*q.UnparsableMessageError)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ErrElicitationNotSupported":                reflect.ValueOf(&q.ErrElicitationNotSupported),
			"ErrNoActiveSession":                        reflect.ValueOf(&q.ErrNoActiveSession),
			"ErrNoClientSession":                        reflect.ValueOf(&q.ErrNoClientSession),
			"ErrNotificationChannelBlocked":             reflect.ValueOf(&q.ErrNotificationChannelBlocked),
			"ErrNotificationNotInitialized":             reflect.ValueOf(&q.ErrNotificationNotInitialized),
			"ErrPromptNotFound":                         reflect.ValueOf(&q.ErrPromptNotFound),
			"ErrResourceNotFound":                       reflect.ValueOf(&q.ErrResourceNotFound),
			"ErrRootsNotSupported":                      reflect.ValueOf(&q.ErrRootsNotSupported),
			"ErrSessionDoesNotSupportLogging":           reflect.ValueOf(&q.ErrSessionDoesNotSupportLogging),
			"ErrSessionDoesNotSupportResourceTemplates": reflect.ValueOf(&q.ErrSessionDoesNotSupportResourceTemplates),
			"ErrSessionDoesNotSupportResources":         reflect.ValueOf(&q.ErrSessionDoesNotSupportResources),
			"ErrSessionDoesNotSupportTools":             reflect.ValueOf(&q.ErrSessionDoesNotSupportTools),
			"ErrSessionExists":                          reflect.ValueOf(&q.ErrSessionExists),
			"ErrSessionNotFound":                        reflect.ValueOf(&q.ErrSessionNotFound),
			"ErrSessionNotInitialized":                  reflect.ValueOf(&q.ErrSessionNotInitialized),
			"ErrToolNotFound":                           reflect.ValueOf(&q.ErrToolNotFound),
			"ErrUnsupported":                            reflect.ValueOf(&q.ErrUnsupported),
		},
		Funcs: map[string]reflect.Value{
			"ClientSessionFromContext":            reflect.ValueOf(q.ClientSessionFromContext),
			"GenerateInProcessSessionID":          reflect.ValueOf(q.GenerateInProcessSessionID),
			"InProcessSamplingHandlerFromContext": reflect.ValueOf(q.InProcessSamplingHandlerFromContext),
			"NewDefaultSessionIdManagerResolver":  reflect.ValueOf(q.NewDefaultSessionIdManagerResolver),
			"NewInProcessSession":                 reflect.ValueOf(q.NewInProcessSession),
			"NewInProcessSessionWithHandlers":     reflect.ValueOf(q.NewInProcessSessionWithHandlers),
			"NewMCPServer":                        reflect.ValueOf(q.NewMCPServer),
			"NewSSEServer":                        reflect.ValueOf(q.NewSSEServer),
			"NewStdioServer":                      reflect.ValueOf(q.NewStdioServer),
			"NewStreamableHTTPServer":             reflect.ValueOf(q.NewStreamableHTTPServer),
			"NewTestServer":                       reflect.ValueOf(q.NewTestServer),
			"NewTestStreamableHTTPServer":         reflect.ValueOf(q.NewTestStreamableHTTPServer),
			"ServeStdio":                          reflect.ValueOf(q.ServeStdio),
			"ServerFromContext":                   reflect.ValueOf(q.ServerFromContext),
			"WithAppendQueryToMessageEndpoint":    reflect.ValueOf(q.WithAppendQueryToMessageEndpoint),
			"WithBasePath":                        reflect.ValueOf(q.WithBasePath),
			"WithBaseURL":                         reflect.ValueOf(q.WithBaseURL),
			"WithDisableStreaming":                reflect.ValueOf(q.WithDisableStreaming),
			"WithDynamicBasePath":                 reflect.ValueOf(q.WithDynamicBasePath),
			"WithElicitation":                     reflect.ValueOf(q.WithElicitation),
			"WithEndpointPath":                    reflect.ValueOf(q.WithEndpointPath),
			"WithErrorLogger":                     reflect.ValueOf(q.WithErrorLogger),
			"WithHTTPContextFunc":                 reflect.ValueOf(q.WithHTTPContextFunc),
			"WithHTTPServer":                      reflect.ValueOf(q.WithHTTPServer),
			"WithHeartbeatInterval":               reflect.ValueOf(q.WithHeartbeatInterval),
			"WithHooks":                           reflect.ValueOf(q.WithHooks),
			"WithInProcessSamplingHandler":        reflect.ValueOf(q.WithInProcessSamplingHandler),
			"WithInstructions":                    reflect.ValueOf(q.WithInstructions),
			"WithKeepAlive":                       reflect.ValueOf(q.WithKeepAlive),
			"WithKeepAliveInterval":               reflect.ValueOf(q.WithKeepAliveInterval),
			"WithLogger":                          reflect.ValueOf(q.WithLogger),
			"WithLogging":                         reflect.ValueOf(q.WithLogging),
			"WithMessageEndpoint":                 reflect.ValueOf(q.WithMessageEndpoint),
			"WithPaginationLimit":                 reflect.ValueOf(q.WithPaginationLimit),
			"WithPromptCapabilities":              reflect.ValueOf(q.WithPromptCapabilities),
			"WithQueueSize":                       reflect.ValueOf(q.WithQueueSize),
			"WithRecovery":                        reflect.ValueOf(q.WithRecovery),
			"WithResourceCapabilities":            reflect.ValueOf(q.WithResourceCapabilities),
			"WithResourceHandlerMiddleware":       reflect.ValueOf(q.WithResourceHandlerMiddleware),
			"WithResourceRecovery":                reflect.ValueOf(q.WithResourceRecovery),
			"WithRoots":                           reflect.ValueOf(q.WithRoots),
			"WithSSEContextFunc":                  reflect.ValueOf(q.WithSSEContextFunc),
			"WithSSEEndpoint":                     reflect.ValueOf(q.WithSSEEndpoint),
			"WithSessionIdManager":                reflect.ValueOf(q.WithSessionIdManager),
			"WithSessionIdManagerResolver":        reflect.ValueOf(q.WithSessionIdManagerResolver),
			"WithStateLess":                       reflect.ValueOf(q.WithStateLess),
			"WithStateful":                        reflect.ValueOf(q.WithStateful),
			"WithStaticBasePath":                  reflect.ValueOf(q.WithStaticBasePath),
			"WithStdioContextFunc":                reflect.ValueOf(q.WithStdioContextFunc),
			"WithStreamableHTTPServer":            reflect.ValueOf(q.WithStreamableHTTPServer),
			"WithTLSCert":                         reflect.ValueOf(q.WithTLSCert),
			"WithToolCapabilities":                reflect.ValueOf(q.WithToolCapabilities),
			"WithToolFilter":                      reflect.ValueOf(q.WithToolFilter),
			"WithToolHandlerMiddleware":           reflect.ValueOf(q.WithToolHandlerMiddleware),
			"WithUseFullURLForMessageEndpoint":    reflect.ValueOf(q.WithUseFullURLForMessageEndpoint),
			"WithWorkerPoolSize":                  reflect.ValueOf(q.WithWorkerPoolSize),
		},
		TypedConsts: map[string]ixgo.TypedConst{},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"HeaderKeyProtocolVersion": {"untyped string", constant.MakeString(string(q.HeaderKeyProtocolVersion))},
			"HeaderKeySessionID":       {"untyped string", constant.MakeString(string(q.HeaderKeySessionID))},
		},
	})
}
