// export by github.com/goplus/ixgo/cmd/qexp

package mcp

import (
	q "github.com/mark3labs/mcp-go/mcp"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "mcp",
		Path: "github.com/mark3labs/mcp-go/mcp",
		Deps: map[string]string{
			"context":                            "context",
			"encoding/json":                      "json",
			"errors":                             "errors",
			"fmt":                                "fmt",
			"github.com/spf13/cast":              "cast",
			"github.com/yosida95/uritemplate/v3": "uritemplate",
			"maps":                               "maps",
			"reflect":                            "reflect",
			"strconv":                            "strconv",
		},
		Interfaces: map[string]reflect.Type{
			"ClientNotification": reflect.TypeOf((*q.ClientNotification)(nil)).Elem(),
			"ClientRequest":      reflect.TypeOf((*q.ClientRequest)(nil)).Elem(),
			"ClientResult":       reflect.TypeOf((*q.ClientResult)(nil)).Elem(),
			"Content":            reflect.TypeOf((*q.Content)(nil)).Elem(),
			"JSONRPCMessage":     reflect.TypeOf((*q.JSONRPCMessage)(nil)).Elem(),
			"Named":              reflect.TypeOf((*q.Named)(nil)).Elem(),
			"ProgressToken":      reflect.TypeOf((*q.ProgressToken)(nil)).Elem(),
			"ResourceContents":   reflect.TypeOf((*q.ResourceContents)(nil)).Elem(),
			"ServerNotification": reflect.TypeOf((*q.ServerNotification)(nil)).Elem(),
			"ServerRequest":      reflect.TypeOf((*q.ServerRequest)(nil)).Elem(),
			"ServerResult":       reflect.TypeOf((*q.ServerResult)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"Annotated":                       reflect.TypeOf((*q.Annotated)(nil)).Elem(),
			"Annotations":                     reflect.TypeOf((*q.Annotations)(nil)).Elem(),
			"ArgumentOption":                  reflect.TypeOf((*q.ArgumentOption)(nil)).Elem(),
			"AudioContent":                    reflect.TypeOf((*q.AudioContent)(nil)).Elem(),
			"BlobResourceContents":            reflect.TypeOf((*q.BlobResourceContents)(nil)).Elem(),
			"CallToolRequest":                 reflect.TypeOf((*q.CallToolRequest)(nil)).Elem(),
			"CallToolResult":                  reflect.TypeOf((*q.CallToolResult)(nil)).Elem(),
			"CancelledNotification":           reflect.TypeOf((*q.CancelledNotification)(nil)).Elem(),
			"ClientCapabilities":              reflect.TypeOf((*q.ClientCapabilities)(nil)).Elem(),
			"CompleteRequest":                 reflect.TypeOf((*q.CompleteRequest)(nil)).Elem(),
			"CompleteResult":                  reflect.TypeOf((*q.CompleteResult)(nil)).Elem(),
			"CreateMessageRequest":            reflect.TypeOf((*q.CreateMessageRequest)(nil)).Elem(),
			"CreateMessageResult":             reflect.TypeOf((*q.CreateMessageResult)(nil)).Elem(),
			"Cursor":                          reflect.TypeOf((*q.Cursor)(nil)).Elem(),
			"EmbeddedResource":                reflect.TypeOf((*q.EmbeddedResource)(nil)).Elem(),
			"EmptyResult":                     reflect.TypeOf((*q.EmptyResult)(nil)).Elem(),
			"GetPromptRequest":                reflect.TypeOf((*q.GetPromptRequest)(nil)).Elem(),
			"GetPromptResult":                 reflect.TypeOf((*q.GetPromptResult)(nil)).Elem(),
			"ImageContent":                    reflect.TypeOf((*q.ImageContent)(nil)).Elem(),
			"Implementation":                  reflect.TypeOf((*q.Implementation)(nil)).Elem(),
			"InitializeRequest":               reflect.TypeOf((*q.InitializeRequest)(nil)).Elem(),
			"InitializeResult":                reflect.TypeOf((*q.InitializeResult)(nil)).Elem(),
			"InitializedNotification":         reflect.TypeOf((*q.InitializedNotification)(nil)).Elem(),
			"JSONRPCError":                    reflect.TypeOf((*q.JSONRPCError)(nil)).Elem(),
			"JSONRPCNotification":             reflect.TypeOf((*q.JSONRPCNotification)(nil)).Elem(),
			"JSONRPCRequest":                  reflect.TypeOf((*q.JSONRPCRequest)(nil)).Elem(),
			"JSONRPCResponse":                 reflect.TypeOf((*q.JSONRPCResponse)(nil)).Elem(),
			"ListPromptsRequest":              reflect.TypeOf((*q.ListPromptsRequest)(nil)).Elem(),
			"ListPromptsResult":               reflect.TypeOf((*q.ListPromptsResult)(nil)).Elem(),
			"ListResourceTemplatesRequest":    reflect.TypeOf((*q.ListResourceTemplatesRequest)(nil)).Elem(),
			"ListResourceTemplatesResult":     reflect.TypeOf((*q.ListResourceTemplatesResult)(nil)).Elem(),
			"ListResourcesRequest":            reflect.TypeOf((*q.ListResourcesRequest)(nil)).Elem(),
			"ListResourcesResult":             reflect.TypeOf((*q.ListResourcesResult)(nil)).Elem(),
			"ListRootsRequest":                reflect.TypeOf((*q.ListRootsRequest)(nil)).Elem(),
			"ListRootsResult":                 reflect.TypeOf((*q.ListRootsResult)(nil)).Elem(),
			"ListToolsRequest":                reflect.TypeOf((*q.ListToolsRequest)(nil)).Elem(),
			"ListToolsResult":                 reflect.TypeOf((*q.ListToolsResult)(nil)).Elem(),
			"LoggingLevel":                    reflect.TypeOf((*q.LoggingLevel)(nil)).Elem(),
			"LoggingMessageNotification":      reflect.TypeOf((*q.LoggingMessageNotification)(nil)).Elem(),
			"MCPMethod":                       reflect.TypeOf((*q.MCPMethod)(nil)).Elem(),
			"Meta":                            reflect.TypeOf((*q.Meta)(nil)).Elem(),
			"ModelHint":                       reflect.TypeOf((*q.ModelHint)(nil)).Elem(),
			"ModelPreferences":                reflect.TypeOf((*q.ModelPreferences)(nil)).Elem(),
			"Notification":                    reflect.TypeOf((*q.Notification)(nil)).Elem(),
			"NotificationParams":              reflect.TypeOf((*q.NotificationParams)(nil)).Elem(),
			"PaginatedRequest":                reflect.TypeOf((*q.PaginatedRequest)(nil)).Elem(),
			"PaginatedResult":                 reflect.TypeOf((*q.PaginatedResult)(nil)).Elem(),
			"Params":                          reflect.TypeOf((*q.Params)(nil)).Elem(),
			"PingRequest":                     reflect.TypeOf((*q.PingRequest)(nil)).Elem(),
			"ProgressNotification":            reflect.TypeOf((*q.ProgressNotification)(nil)).Elem(),
			"Prompt":                          reflect.TypeOf((*q.Prompt)(nil)).Elem(),
			"PromptArgument":                  reflect.TypeOf((*q.PromptArgument)(nil)).Elem(),
			"PromptListChangedNotification":   reflect.TypeOf((*q.PromptListChangedNotification)(nil)).Elem(),
			"PromptMessage":                   reflect.TypeOf((*q.PromptMessage)(nil)).Elem(),
			"PromptOption":                    reflect.TypeOf((*q.PromptOption)(nil)).Elem(),
			"PromptReference":                 reflect.TypeOf((*q.PromptReference)(nil)).Elem(),
			"PropertyOption":                  reflect.TypeOf((*q.PropertyOption)(nil)).Elem(),
			"ReadResourceRequest":             reflect.TypeOf((*q.ReadResourceRequest)(nil)).Elem(),
			"ReadResourceResult":              reflect.TypeOf((*q.ReadResourceResult)(nil)).Elem(),
			"Request":                         reflect.TypeOf((*q.Request)(nil)).Elem(),
			"RequestId":                       reflect.TypeOf((*q.RequestId)(nil)).Elem(),
			"Resource":                        reflect.TypeOf((*q.Resource)(nil)).Elem(),
			"ResourceListChangedNotification": reflect.TypeOf((*q.ResourceListChangedNotification)(nil)).Elem(),
			"ResourceOption":                  reflect.TypeOf((*q.ResourceOption)(nil)).Elem(),
			"ResourceReference":               reflect.TypeOf((*q.ResourceReference)(nil)).Elem(),
			"ResourceTemplate":                reflect.TypeOf((*q.ResourceTemplate)(nil)).Elem(),
			"ResourceTemplateOption":          reflect.TypeOf((*q.ResourceTemplateOption)(nil)).Elem(),
			"ResourceUpdatedNotification":     reflect.TypeOf((*q.ResourceUpdatedNotification)(nil)).Elem(),
			"Result":                          reflect.TypeOf((*q.Result)(nil)).Elem(),
			"Role":                            reflect.TypeOf((*q.Role)(nil)).Elem(),
			"Root":                            reflect.TypeOf((*q.Root)(nil)).Elem(),
			"RootsListChangedNotification":    reflect.TypeOf((*q.RootsListChangedNotification)(nil)).Elem(),
			"SamplingMessage":                 reflect.TypeOf((*q.SamplingMessage)(nil)).Elem(),
			"ServerCapabilities":              reflect.TypeOf((*q.ServerCapabilities)(nil)).Elem(),
			"SetLevelRequest":                 reflect.TypeOf((*q.SetLevelRequest)(nil)).Elem(),
			"SubscribeRequest":                reflect.TypeOf((*q.SubscribeRequest)(nil)).Elem(),
			"TextContent":                     reflect.TypeOf((*q.TextContent)(nil)).Elem(),
			"TextResourceContents":            reflect.TypeOf((*q.TextResourceContents)(nil)).Elem(),
			"Tool":                            reflect.TypeOf((*q.Tool)(nil)).Elem(),
			"ToolAnnotation":                  reflect.TypeOf((*q.ToolAnnotation)(nil)).Elem(),
			"ToolInputSchema":                 reflect.TypeOf((*q.ToolInputSchema)(nil)).Elem(),
			"ToolListChangedNotification":     reflect.TypeOf((*q.ToolListChangedNotification)(nil)).Elem(),
			"ToolOption":                      reflect.TypeOf((*q.ToolOption)(nil)).Elem(),
			"URITemplate":                     reflect.TypeOf((*q.URITemplate)(nil)).Elem(),
			"UnsubscribeRequest":              reflect.TypeOf((*q.UnsubscribeRequest)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{},
		Vars:       map[string]reflect.Value{},
		Funcs: map[string]reflect.Value{
			"AdditionalProperties":           reflect.ValueOf(q.AdditionalProperties),
			"ArgumentDescription":            reflect.ValueOf(q.ArgumentDescription),
			"AsAudioContent":                 reflect.ValueOf(q.AsAudioContent),
			"AsBlobResourceContents":         reflect.ValueOf(q.AsBlobResourceContents),
			"AsEmbeddedResource":             reflect.ValueOf(q.AsEmbeddedResource),
			"AsImageContent":                 reflect.ValueOf(q.AsImageContent),
			"AsTextContent":                  reflect.ValueOf(q.AsTextContent),
			"AsTextResourceContents":         reflect.ValueOf(q.AsTextResourceContents),
			"DefaultBool":                    reflect.ValueOf(q.DefaultBool),
			"DefaultNumber":                  reflect.ValueOf(q.DefaultNumber),
			"DefaultString":                  reflect.ValueOf(q.DefaultString),
			"Description":                    reflect.ValueOf(q.Description),
			"Enum":                           reflect.ValueOf(q.Enum),
			"ExtractMap":                     reflect.ValueOf(q.ExtractMap),
			"ExtractString":                  reflect.ValueOf(q.ExtractString),
			"FormatNumberResult":             reflect.ValueOf(q.FormatNumberResult),
			"Items":                          reflect.ValueOf(q.Items),
			"Max":                            reflect.ValueOf(q.Max),
			"MaxItems":                       reflect.ValueOf(q.MaxItems),
			"MaxLength":                      reflect.ValueOf(q.MaxLength),
			"MaxProperties":                  reflect.ValueOf(q.MaxProperties),
			"Min":                            reflect.ValueOf(q.Min),
			"MinItems":                       reflect.ValueOf(q.MinItems),
			"MinLength":                      reflect.ValueOf(q.MinLength),
			"MinProperties":                  reflect.ValueOf(q.MinProperties),
			"MultipleOf":                     reflect.ValueOf(q.MultipleOf),
			"NewAudioContent":                reflect.ValueOf(q.NewAudioContent),
			"NewEmbeddedResource":            reflect.ValueOf(q.NewEmbeddedResource),
			"NewGetPromptResult":             reflect.ValueOf(q.NewGetPromptResult),
			"NewImageContent":                reflect.ValueOf(q.NewImageContent),
			"NewInitializeResult":            reflect.ValueOf(q.NewInitializeResult),
			"NewJSONRPCError":                reflect.ValueOf(q.NewJSONRPCError),
			"NewJSONRPCResponse":             reflect.ValueOf(q.NewJSONRPCResponse),
			"NewListPromptsResult":           reflect.ValueOf(q.NewListPromptsResult),
			"NewListResourceTemplatesResult": reflect.ValueOf(q.NewListResourceTemplatesResult),
			"NewListResourcesResult":         reflect.ValueOf(q.NewListResourcesResult),
			"NewListToolsResult":             reflect.ValueOf(q.NewListToolsResult),
			"NewLoggingMessageNotification":  reflect.ValueOf(q.NewLoggingMessageNotification),
			"NewProgressNotification":        reflect.ValueOf(q.NewProgressNotification),
			"NewPrompt":                      reflect.ValueOf(q.NewPrompt),
			"NewPromptMessage":               reflect.ValueOf(q.NewPromptMessage),
			"NewReadResourceResult":          reflect.ValueOf(q.NewReadResourceResult),
			"NewRequestId":                   reflect.ValueOf(q.NewRequestId),
			"NewResource":                    reflect.ValueOf(q.NewResource),
			"NewResourceTemplate":            reflect.ValueOf(q.NewResourceTemplate),
			"NewTextContent":                 reflect.ValueOf(q.NewTextContent),
			"NewTool":                        reflect.ValueOf(q.NewTool),
			"NewToolResultAudio":             reflect.ValueOf(q.NewToolResultAudio),
			"NewToolResultError":             reflect.ValueOf(q.NewToolResultError),
			"NewToolResultErrorFromErr":      reflect.ValueOf(q.NewToolResultErrorFromErr),
			"NewToolResultImage":             reflect.ValueOf(q.NewToolResultImage),
			"NewToolResultResource":          reflect.ValueOf(q.NewToolResultResource),
			"NewToolResultText":              reflect.ValueOf(q.NewToolResultText),
			"NewToolWithRawSchema":           reflect.ValueOf(q.NewToolWithRawSchema),
			"ParseArgument":                  reflect.ValueOf(q.ParseArgument),
			"ParseBoolean":                   reflect.ValueOf(q.ParseBoolean),
			"ParseCallToolResult":            reflect.ValueOf(q.ParseCallToolResult),
			"ParseContent":                   reflect.ValueOf(q.ParseContent),
			"ParseFloat32":                   reflect.ValueOf(q.ParseFloat32),
			"ParseFloat64":                   reflect.ValueOf(q.ParseFloat64),
			"ParseGetPromptResult":           reflect.ValueOf(q.ParseGetPromptResult),
			"ParseInt":                       reflect.ValueOf(q.ParseInt),
			"ParseInt16":                     reflect.ValueOf(q.ParseInt16),
			"ParseInt32":                     reflect.ValueOf(q.ParseInt32),
			"ParseInt64":                     reflect.ValueOf(q.ParseInt64),
			"ParseInt8":                      reflect.ValueOf(q.ParseInt8),
			"ParseReadResourceResult":        reflect.ValueOf(q.ParseReadResourceResult),
			"ParseResourceContents":          reflect.ValueOf(q.ParseResourceContents),
			"ParseString":                    reflect.ValueOf(q.ParseString),
			"ParseStringMap":                 reflect.ValueOf(q.ParseStringMap),
			"ParseUInt":                      reflect.ValueOf(q.ParseUInt),
			"ParseUInt16":                    reflect.ValueOf(q.ParseUInt16),
			"ParseUInt32":                    reflect.ValueOf(q.ParseUInt32),
			"ParseUInt64":                    reflect.ValueOf(q.ParseUInt64),
			"ParseUInt8":                     reflect.ValueOf(q.ParseUInt8),
			"Pattern":                        reflect.ValueOf(q.Pattern),
			"Properties":                     reflect.ValueOf(q.Properties),
			"PropertyNames":                  reflect.ValueOf(q.PropertyNames),
			"Required":                       reflect.ValueOf(q.Required),
			"RequiredArgument":               reflect.ValueOf(q.RequiredArgument),
			"Title":                          reflect.ValueOf(q.Title),
			"ToBoolPtr":                      reflect.ValueOf(q.ToBoolPtr),
			"UniqueItems":                    reflect.ValueOf(q.UniqueItems),
			"WithAnnotations":                reflect.ValueOf(q.WithAnnotations),
			"WithArgument":                   reflect.ValueOf(q.WithArgument),
			"WithArray":                      reflect.ValueOf(q.WithArray),
			"WithBoolean":                    reflect.ValueOf(q.WithBoolean),
			"WithDescription":                reflect.ValueOf(q.WithDescription),
			"WithDestructiveHintAnnotation":  reflect.ValueOf(q.WithDestructiveHintAnnotation),
			"WithIdempotentHintAnnotation":   reflect.ValueOf(q.WithIdempotentHintAnnotation),
			"WithMIMEType":                   reflect.ValueOf(q.WithMIMEType),
			"WithNumber":                     reflect.ValueOf(q.WithNumber),
			"WithObject":                     reflect.ValueOf(q.WithObject),
			"WithOpenWorldHintAnnotation":    reflect.ValueOf(q.WithOpenWorldHintAnnotation),
			"WithPromptDescription":          reflect.ValueOf(q.WithPromptDescription),
			"WithReadOnlyHintAnnotation":     reflect.ValueOf(q.WithReadOnlyHintAnnotation),
			"WithResourceDescription":        reflect.ValueOf(q.WithResourceDescription),
			"WithString":                     reflect.ValueOf(q.WithString),
			"WithTemplateAnnotations":        reflect.ValueOf(q.WithTemplateAnnotations),
			"WithTemplateDescription":        reflect.ValueOf(q.WithTemplateDescription),
			"WithTemplateMIMEType":           reflect.ValueOf(q.WithTemplateMIMEType),
			"WithTitleAnnotation":            reflect.ValueOf(q.WithTitleAnnotation),
			"WithToolAnnotation":             reflect.ValueOf(q.WithToolAnnotation),
		},
		TypedConsts: map[string]ixgo.TypedConst{
			"LoggingLevelAlert":            {reflect.TypeOf(q.LoggingLevelAlert), constant.MakeString(string(q.LoggingLevelAlert))},
			"LoggingLevelCritical":         {reflect.TypeOf(q.LoggingLevelCritical), constant.MakeString(string(q.LoggingLevelCritical))},
			"LoggingLevelDebug":            {reflect.TypeOf(q.LoggingLevelDebug), constant.MakeString(string(q.LoggingLevelDebug))},
			"LoggingLevelEmergency":        {reflect.TypeOf(q.LoggingLevelEmergency), constant.MakeString(string(q.LoggingLevelEmergency))},
			"LoggingLevelError":            {reflect.TypeOf(q.LoggingLevelError), constant.MakeString(string(q.LoggingLevelError))},
			"LoggingLevelInfo":             {reflect.TypeOf(q.LoggingLevelInfo), constant.MakeString(string(q.LoggingLevelInfo))},
			"LoggingLevelNotice":           {reflect.TypeOf(q.LoggingLevelNotice), constant.MakeString(string(q.LoggingLevelNotice))},
			"LoggingLevelWarning":          {reflect.TypeOf(q.LoggingLevelWarning), constant.MakeString(string(q.LoggingLevelWarning))},
			"MethodInitialize":             {reflect.TypeOf(q.MethodInitialize), constant.MakeString(string(q.MethodInitialize))},
			"MethodPing":                   {reflect.TypeOf(q.MethodPing), constant.MakeString(string(q.MethodPing))},
			"MethodPromptsGet":             {reflect.TypeOf(q.MethodPromptsGet), constant.MakeString(string(q.MethodPromptsGet))},
			"MethodPromptsList":            {reflect.TypeOf(q.MethodPromptsList), constant.MakeString(string(q.MethodPromptsList))},
			"MethodResourcesList":          {reflect.TypeOf(q.MethodResourcesList), constant.MakeString(string(q.MethodResourcesList))},
			"MethodResourcesRead":          {reflect.TypeOf(q.MethodResourcesRead), constant.MakeString(string(q.MethodResourcesRead))},
			"MethodResourcesTemplatesList": {reflect.TypeOf(q.MethodResourcesTemplatesList), constant.MakeString(string(q.MethodResourcesTemplatesList))},
			"MethodSetLogLevel":            {reflect.TypeOf(q.MethodSetLogLevel), constant.MakeString(string(q.MethodSetLogLevel))},
			"MethodToolsCall":              {reflect.TypeOf(q.MethodToolsCall), constant.MakeString(string(q.MethodToolsCall))},
			"MethodToolsList":              {reflect.TypeOf(q.MethodToolsList), constant.MakeString(string(q.MethodToolsList))},
			"RoleAssistant":                {reflect.TypeOf(q.RoleAssistant), constant.MakeString(string(q.RoleAssistant))},
			"RoleUser":                     {reflect.TypeOf(q.RoleUser), constant.MakeString(string(q.RoleUser))},
		},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"INTERNAL_ERROR":                         {"untyped int", constant.MakeInt64(int64(q.INTERNAL_ERROR))},
			"INVALID_PARAMS":                         {"untyped int", constant.MakeInt64(int64(q.INVALID_PARAMS))},
			"INVALID_REQUEST":                        {"untyped int", constant.MakeInt64(int64(q.INVALID_REQUEST))},
			"JSONRPC_VERSION":                        {"untyped string", constant.MakeString(string(q.JSONRPC_VERSION))},
			"LATEST_PROTOCOL_VERSION":                {"untyped string", constant.MakeString(string(q.LATEST_PROTOCOL_VERSION))},
			"METHOD_NOT_FOUND":                       {"untyped int", constant.MakeInt64(int64(q.METHOD_NOT_FOUND))},
			"MethodNotificationPromptsListChanged":   {"untyped string", constant.MakeString(string(q.MethodNotificationPromptsListChanged))},
			"MethodNotificationResourceUpdated":      {"untyped string", constant.MakeString(string(q.MethodNotificationResourceUpdated))},
			"MethodNotificationResourcesListChanged": {"untyped string", constant.MakeString(string(q.MethodNotificationResourcesListChanged))},
			"MethodNotificationToolsListChanged":     {"untyped string", constant.MakeString(string(q.MethodNotificationToolsListChanged))},
			"PARSE_ERROR":                            {"untyped int", constant.MakeInt64(int64(q.PARSE_ERROR))},
			"RESOURCE_NOT_FOUND":                     {"untyped int", constant.MakeInt64(int64(q.RESOURCE_NOT_FOUND))},
		},
	})
}
