// export by github.com/goplus/ixgo/cmd/qexp

package transport

import (
	q "github.com/mark3labs/mcp-go/client/transport"

	"go/constant"
	"reflect"

	"github.com/goplus/ixgo"
)

func init() {
	ixgo.RegisterPackage(&ixgo.Package{
		Name: "transport",
		Path: "github.com/mark3labs/mcp-go/client/transport",
		Deps: map[string]string{
			"bufio":                              "bufio",
			"bytes":                              "bytes",
			"context":                            "context",
			"crypto/rand":                        "rand",
			"crypto/sha256":                      "sha256",
			"encoding/base64":                    "base64",
			"encoding/json":                      "json",
			"errors":                             "errors",
			"fmt":                                "fmt",
			"github.com/mark3labs/mcp-go/mcp":    "mcp",
			"github.com/mark3labs/mcp-go/server": "server",
			"github.com/mark3labs/mcp-go/util":   "util",
			"io":                                 "io",
			"mime":                               "mime",
			"net/http":                           "http",
			"net/url":                            "url",
			"os":                                 "os",
			"os/exec":                            "exec",
			"strings":                            "strings",
			"sync":                               "sync",
			"sync/atomic":                        "atomic",
			"time":                               "time",
		},
		Interfaces: map[string]reflect.Type{
			"BidirectionalInterface": reflect.TypeOf((*q.BidirectionalInterface)(nil)).Elem(),
			"HTTPConnection":         reflect.TypeOf((*q.HTTPConnection)(nil)).Elem(),
			"Interface":              reflect.TypeOf((*q.Interface)(nil)).Elem(),
			"TokenStore":             reflect.TypeOf((*q.TokenStore)(nil)).Elem(),
		},
		NamedTypes: map[string]reflect.Type{
			"AuthServerMetadata":              reflect.TypeOf((*q.AuthServerMetadata)(nil)).Elem(),
			"ClientOption":                    reflect.TypeOf((*q.ClientOption)(nil)).Elem(),
			"CommandFunc":                     reflect.TypeOf((*q.CommandFunc)(nil)).Elem(),
			"Error":                           reflect.TypeOf((*q.Error)(nil)).Elem(),
			"HTTPHeaderFunc":                  reflect.TypeOf((*q.HTTPHeaderFunc)(nil)).Elem(),
			"InProcessOption":                 reflect.TypeOf((*q.InProcessOption)(nil)).Elem(),
			"InProcessTransport":              reflect.TypeOf((*q.InProcessTransport)(nil)).Elem(),
			"JSONRPCRequest":                  reflect.TypeOf((*q.JSONRPCRequest)(nil)).Elem(),
			"JSONRPCResponse":                 reflect.TypeOf((*q.JSONRPCResponse)(nil)).Elem(),
			"MemoryTokenStore":                reflect.TypeOf((*q.MemoryTokenStore)(nil)).Elem(),
			"OAuthAuthorizationRequiredError": reflect.TypeOf((*q.OAuthAuthorizationRequiredError)(nil)).Elem(),
			"OAuthConfig":                     reflect.TypeOf((*q.OAuthConfig)(nil)).Elem(),
			"OAuthError":                      reflect.TypeOf((*q.OAuthError)(nil)).Elem(),
			"OAuthHandler":                    reflect.TypeOf((*q.OAuthHandler)(nil)).Elem(),
			"OAuthProtectedResource":          reflect.TypeOf((*q.OAuthProtectedResource)(nil)).Elem(),
			"RequestHandler":                  reflect.TypeOf((*q.RequestHandler)(nil)).Elem(),
			"SSE":                             reflect.TypeOf((*q.SSE)(nil)).Elem(),
			"Stdio":                           reflect.TypeOf((*q.Stdio)(nil)).Elem(),
			"StdioOption":                     reflect.TypeOf((*q.StdioOption)(nil)).Elem(),
			"StreamableHTTP":                  reflect.TypeOf((*q.StreamableHTTP)(nil)).Elem(),
			"StreamableHTTPCOption":           reflect.TypeOf((*q.StreamableHTTPCOption)(nil)).Elem(),
			"Token":                           reflect.TypeOf((*q.Token)(nil)).Elem(),
		},
		AliasTypes: map[string]reflect.Type{},
		Vars: map[string]reflect.Value{
			"ErrGetMethodNotAllowed":        reflect.ValueOf(&q.ErrGetMethodNotAllowed),
			"ErrInvalidState":               reflect.ValueOf(&q.ErrInvalidState),
			"ErrNoToken":                    reflect.ValueOf(&q.ErrNoToken),
			"ErrOAuthAuthorizationRequired": reflect.ValueOf(&q.ErrOAuthAuthorizationRequired),
			"ErrSessionTerminated":          reflect.ValueOf(&q.ErrSessionTerminated),
		},
		Funcs: map[string]reflect.Value{
			"GenerateCodeChallenge":            reflect.ValueOf(q.GenerateCodeChallenge),
			"GenerateCodeVerifier":             reflect.ValueOf(q.GenerateCodeVerifier),
			"GenerateRandomString":             reflect.ValueOf(q.GenerateRandomString),
			"GenerateState":                    reflect.ValueOf(q.GenerateState),
			"NewError":                         reflect.ValueOf(q.NewError),
			"NewIO":                            reflect.ValueOf(q.NewIO),
			"NewInProcessTransport":            reflect.ValueOf(q.NewInProcessTransport),
			"NewInProcessTransportWithOptions": reflect.ValueOf(q.NewInProcessTransportWithOptions),
			"NewJSONRPCErrorResponse":          reflect.ValueOf(q.NewJSONRPCErrorResponse),
			"NewJSONRPCResultResponse":         reflect.ValueOf(q.NewJSONRPCResultResponse),
			"NewMemoryTokenStore":              reflect.ValueOf(q.NewMemoryTokenStore),
			"NewOAuthHandler":                  reflect.ValueOf(q.NewOAuthHandler),
			"NewSSE":                           reflect.ValueOf(q.NewSSE),
			"NewStdio":                         reflect.ValueOf(q.NewStdio),
			"NewStdioWithOptions":              reflect.ValueOf(q.NewStdioWithOptions),
			"NewStreamableHTTP":                reflect.ValueOf(q.NewStreamableHTTP),
			"ValidateRedirectURI":              reflect.ValueOf(q.ValidateRedirectURI),
			"WithCommandFunc":                  reflect.ValueOf(q.WithCommandFunc),
			"WithCommandLogger":                reflect.ValueOf(q.WithCommandLogger),
			"WithContinuousListening":          reflect.ValueOf(q.WithContinuousListening),
			"WithElicitationHandler":           reflect.ValueOf(q.WithElicitationHandler),
			"WithHTTPBasicClient":              reflect.ValueOf(q.WithHTTPBasicClient),
			"WithHTTPClient":                   reflect.ValueOf(q.WithHTTPClient),
			"WithHTTPHeaderFunc":               reflect.ValueOf(q.WithHTTPHeaderFunc),
			"WithHTTPHeaders":                  reflect.ValueOf(q.WithHTTPHeaders),
			"WithHTTPLogger":                   reflect.ValueOf(q.WithHTTPLogger),
			"WithHTTPOAuth":                    reflect.ValueOf(q.WithHTTPOAuth),
			"WithHTTPTimeout":                  reflect.ValueOf(q.WithHTTPTimeout),
			"WithHeaderFunc":                   reflect.ValueOf(q.WithHeaderFunc),
			"WithHeaders":                      reflect.ValueOf(q.WithHeaders),
			"WithLogger":                       reflect.ValueOf(q.WithLogger),
			"WithOAuth":                        reflect.ValueOf(q.WithOAuth),
			"WithRootsHandler":                 reflect.ValueOf(q.WithRootsHandler),
			"WithSSELogger":                    reflect.ValueOf(q.WithSSELogger),
			"WithSamplingHandler":              reflect.ValueOf(q.WithSamplingHandler),
			"WithSession":                      reflect.ValueOf(q.WithSession),
		},
		TypedConsts: map[string]ixgo.TypedConst{},
		UntypedConsts: map[string]ixgo.UntypedConst{
			"HeaderKeyProtocolVersion": {"untyped string", constant.MakeString(string(q.HeaderKeyProtocolVersion))},
			"HeaderKeySessionID":       {"untyped string", constant.MakeString(string(q.HeaderKeySessionID))},
		},
	})
}
